blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('article/<int:pk>/', views.article, name='article')
]

dinosaur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blog import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('mdeditor/', include('mdeditor.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

blog/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.html import format_html
from django.utils.timezone import now
from mdeditor.fields import MDTextField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Article(MPTTModel):
    ARTICLE_STATUS = (
        ('p', '发布'),
        ('d', '草稿')
    )
    title = models.CharField(max_length=64, verbose_name='标题')
    is_article = models.BooleanField(default=True, verbose_name='是否文章')
    is_category = models.BooleanField(default=False, verbose_name='是否分类目录')  # 允许一篇文章有子节点，即作为一个分类
    content = MDTextField(verbose_name='内容', null=True, blank=True)
    cover = models.ImageField(verbose_name='封面', null=True, blank=True, upload_to='images')
    summary = models.CharField(max_length=200, verbose_name='摘要', null=True, blank=True)
    status = models.CharField(max_length=1, verbose_name="状态", choices=ARTICLE_STATUS, default='p')
    pub_date = models.DateTimeField(verbose_name="发表日期", default=now)
    tags = models.ManyToManyField('Tag', verbose_name='标签', default=None, blank=True)
    views = models.PositiveIntegerField(verbose_name='浏览量', default=0)
    parent = TreeForeignKey('self', verbose_name='父级目录', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children')

    def first_article(self):
        articles = self.get_root().get_descendants()
        for article in articles:
            if article.is_article and article.status == 'p':
                return article
        return None

    def __str__(self):
        return self.title

    def color_title(self):
        if self.is_article:
            title = "<span style='color:lime;'>{0}</span>".format(self.title)
            return format_html(title)
        return ""

    def next(self):
        root = self.get_root();
        articles = root.get_descendants()
        found = False
        for article in articles:
            if found and article.is_article and article.status == 'p':
                return article
            if article.id == self.id:
                found = True
        return None

    def prev(self):
        articles = self.get_root().get_descendants()
        p = None
        for article in articles:
            if article.id == self.id:
                break
            elif article.is_article and article.status == 'p':
                p = article
        return p

    class Meta:
        verbose_name = "文章/目录"
        verbose_name_plural = "文章/目录"

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    class MPTTMeta:
        pass


class Tag(models.Model):
    name = models.CharField('标签名', max_length=30, unique=True)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    def __str__(self):
        return self.name

    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name

class BlogSettings(models.Model):
    '''站点设置 '''
    sitename = models.CharField("网站名称", max_length=200, null=False, blank=False, default='')
    site_description = models.TextField("网站描述", max_length=1000, null=False, blank=False, default='')
    site_seo_description = models.TextField("网站SEO描述", max_length=1000, null=False, blank=False, default='')
    site_keywords = models.TextField("网站关键字", max_length=1000, null=False, blank=False, default='')
    article_sub_length = models.IntegerField("文章摘要长度", default=300)
    sidebar_article_count = models.IntegerField("侧边栏文章数目", default=10)
    sidebar_comment_count = models.IntegerField("侧边栏评论数目", default=5)
    show_google_adsense = models.BooleanField('是否显示谷歌广告', default=False)
    google_adsense_codes = models.TextField('广告内容', max_length=2000, null=True, blank=True, default='')
    open_site_comment = models.BooleanField('是否打开网站评论功能', default=True)
    beiancode = models.CharField('备案号', max_length=2000, null=True, blank=True, default='')
    analyticscode = models.TextField("网站统计代码", max_length=1000, null=True, blank=True, default='')
    show_gongan_code = models.BooleanField('是否显示公安备案号', default=False, null=False)
    gongan_beiancode = models.TextField('公安备案号', max_length=2000, null=True, blank=True, default='')
    resource_path = models.CharField("静态文件保存地址", max_length=300, null=False, default='/var/www/resource/')

    class Meta:
        verbose_name = '网站配置'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sitename

    def clean(self):
        if BlogSettings.objects.exclude(id=self.id).count():
            raise ValidationError('只能有一个配置')

    """
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from DjangoBlog.utils import cache
        cache.clear()
    """


class BlogConfig(models.Model):
    VALUE_TYPE = (
        ('s', "字符串"),
        ('i', "整数"),
        ('d', '小数'),
        ('b', "布尔值")
    )
    name = models.CharField(verbose_name="配置名称", max_length=20, unique=True)
    key = models.CharField(verbose_name="Key", max_length=20, unique=True)
    value = models.CharField(verbose_name="值", max_length=300, blank=True, null=True)
    desc = models.TextField(verbose_name="配置项描述", blank=True, null=True)
    value_type = models.CharField('值类型', max_length=1, choices=VALUE_TYPE, default='s')

    def __str__(self):
        return self.name + " => " + self.value

    def get_value(self):
        if self.value:
            if self.value_type == 'i':
                return int(self.value)
            elif self.value_type == 'b':
                return bool(self.value)
            elif self.value_type == 'd':
                return float(self.value)
            else:
                return self.value
        return None

    @staticmethod
    def insert_default_config():
        BlogConfig(name="Github", key="GITHUB_HOME", value="", desc="Github", value_type="s").save()
        BlogConfig(name='网站名称', key='SITE_NAME', value="", desc="", value_type="s").save()
        BlogConfig(name='网站SEO描述', key='SITE_SEO_DESCRIPTION', value="", desc="", value_type="s").save()
        BlogConfig(name='网站描述', key='SITE_DESCRIPTION', value="", desc="", value_type="s").save()
        BlogConfig(name='网站关键字', key='SITE_KEYWORDS', value="", desc="", value_type="s").save()
        BlogConfig(name='网站URL', key='SITE_BASE_URL', value="", desc="", value_type="s").save()
        BlogConfig(name='文章摘要字数', key='ARTICLE_SUB_LENGTH', value="", desc="", value_type="i").save()
        BlogConfig(name='开启评论', key='OPEN_SITE_COMMENT', value="", desc="", value_type="s").save()
        BlogConfig(name='备案代码', key='BEIAN_CODE', value="", desc="", value_type="s").save()
        BlogConfig(name='统计代码', key='ANALYTICS_CODE', value="", desc="", value_type="s").save()
        BlogConfig(name='公安备案', key="BEIAN_CODE_GONGAN", value="", desc="", value_type="s").save()
        BlogConfig(name='显示公安备案', key="SHOW_GONGAN_CODE", value="", desc="", value_type="b").save()

    class Meta:
        verbose_name = '参数配置'
        verbose_name_plural = verbose_name

blog/views.py
import markdown

from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.utils.text import slugify
from django.views.generic import ListView
from markdown.extensions.toc import TocExtension

from blog.models import Article


class IndexView(ListView):
    template_name = "blog/index.html"


def index(request):
    return render(request, "blog/index.html", {"model": Article.objects.filter(parent=None)})


def article(request, pk):
    model = get_object_or_404(Article, id=pk)
    model.viewed()
    root = model.get_root()

    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    content = md.convert(model.content)
    toc = md.toc
    context = {'model': model, 'root': root, 'content': content, 'toc': toc}
    return render(request, 'blog/article.html', context)


def page_not_found(request, exception):
    return redirect("/", False, {"msg": "404 Page NOT found!"})

templates/blog/article.html
{% extends './layout.html' %}
{% load mptt_tags %}
{% load static %}

{% block header %}
    <title>{{ model.title }} | {{ SITE_DESCRIPTION }}</title>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ model.title }}"/>


    <meta property="og:description" content="{{ model.summary }}"/>


    {% for t in model.tags.all %}
        <meta property="article:tag" content="{{ t.name }}"/>
    {% endfor %}
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

    <meta name="description" content="{{ model.summary }}"/>
    {% if model.tags %}
        <meta name="keywords" content="{{ model.tags.all|join:"," }}"/>
    {% else %}
        <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    {% endif %}

    <link rel="stylesheet" href="{% static 'vendor/font-awesome-4.7.0/css/font-awesome.css' %}">
    <link href="{% static '/vendor/bstree/css/bstree.css' %}" rel="stylesheet"/>
    <link href="{% static '/blog/css/code.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="mb-4">
                <h1 class="mt-4">{{ model.title }}</h1>
                    <div class="mt-1">
                        {{ toc | safe }}
                    </div>
                <div class="mt-4 article">
                    {{ content | safe }}
                </div>
            </div>
            <nav aria-label="Page navigation mt-4">
                <ul class="pagination row">
                    {% with prev=model.prev %}
                        {% if prev %}
                            <li class="pate-item col-md-6"><a
                                    href="{% url 'blog:article' prev.id %}">&larr; {{ prev.title }}</a>
                            </li>
                        {% else %}
                            <li class="pate-item col-md-6"><a class="disabled" href="javascript:void(0);">&larr; 没有了</a>
                            </li>
                        {% endif %}
                    {% endwith %}
                    {% with next=model.next %}
                        {% if next %}
                            <li class="pate-item col-md-6 text-md-right text-xs-left"><a
                                    href="{% url 'blog:article' next.id %}">{{ next.title }} &rarr;</a></li>
                        {% else %}
                            <li class="page-item col-md-6 text-md-right text-xs-left"><a class="disabled"
                                                                                         href="javascript:void(0);">没有了
                                &rarr;</a></li>
                        {% endif %}
                    {% endwith %}
                </ul>
            </nav>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 bg-light border-right border-left">
            <div class="sidebar-heading  mt-4"><strong>{{ root.title }}</strong></div>
            <div id="mytree" class="bstree list-group list-group-flush  mt-1">
                {% with menu=root.get_descendants %}
                    <ul style="padding-inline-start: 1em">
                        {% recursetree menu %}
                            {% if node.is_leaf_node %}
                                <li data-level={{ node.level }} data-link="{% url 'blog:article' node.id %}">
                                    {% else %}
                                <li data-level={{ node.level }}>
                            {% endif %}
                        <span class="label label-default">{{ node.title }}</span>
                        {% if not node.is_leaf_node %}
                            <ul class="children">
                                {{ children }}
                            </ul>
                        {% endif %}
                        </li>
                        {% endrecursetree %}
                    </ul>
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra-js %}
    <script src="{% static '/vendor/bstree/js/jquery.bstree.js' %}"></script>
    <script>
        $('document').ready(function () {
            $('#mytree').bstree({
                isExpanded: window.screen.width > 768,
                updateNodeTitle: function (node, title) {
                    if (node.attr('data-link'))
                        return "<a href='" + node.attr('data-link') + "'>" + title + "</a>";
                    else
                        return title
                }
            });
        })
    </script>
{% endblock %}

templates/blog/index.html
{% extends './layout.html' %}

{% block header %}
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}

{% block content %}
    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
        <h1 class="display-3">{{ SITE_NAME }}</h1>
        <p class="lead">{{ SITE_DESCRIPTION }}</p>
        <p class="lead">欢迎访问！</p>
    </header>

    <!-- Page Features -->
    <div>
        {% for topic in model %}
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title">{{ topic.title }}</h4>
                    <p class="card-text">{{ topic.summary | safe }}</p>
                    {% with article=topic.first_article %}
                        {%  if article %}
                            <a href="{% url 'blog:article' article.id %} " class="card-link">点击阅读</a>
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static '/blog/css/heroic-features.css' %}" rel="stylesheet">
    {% block header %}
    {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">{{ SITE_NAME }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    {% if ABOUT_PAGE %}
                    <a class="nav-link" href="{{ ABOUT_PAGE }}">关于</a>
                    {% else %}
                    <a class="nav-link" href="/">关于</a>
                    {% endif %}
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link" href="/">Services</a>
                </li>
                -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ GITHUB_HOME }}" target="_blank">GITHUB</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; <a href="{% url 'blog:index' %}">{{ SITE_NAME }}</a></p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
{% if ANALYTICS_CODE %}
    {{ ANALYTICS_CODE | safe }}
{% endif %}
{% block extra-js %}
{% endblock %}
</body>

</html>